In [1]:
# https://www.kaggle.com/airbnb/seattle
# 上のサイトからダウンロードしたデータセット

In [2]:
import datetime
import graphviz
import itertools
import os
import platform
import socket
import sys
import time
import warnings
import category_encoders as ce
import lightgbm as lgb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pandas_profiling as pdp
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from tqdm import tqdm
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 300)
sys.path.insert(0, '../utils/')
from utils import *

In [3]:
start("airbnb_seattle_review")

================================================================================
DATE: 2019-04-05 11:12:02.791075
FILE: airbnb_seattle_review
PID: 12692
HOST: Y-project-11
ENV: Windows-10-10.0.17134-SP0
================================================================================

In [8]:
file_name = "../data/input/airbnb_seattle/reviews.csv"
dtypes = {
    "listing_id":"category",
    "id":"category",
    "date":"object",
    "reviewr_id":"category",
    "reviewr_name":"category",
    "comments":"object"
}
datetime_col = {
    "date"
}
with timer("read"):
    df = pd.read_csv(file_name, header=0, index_col=None, sep=',', dtype=dtypes)

[read] start
[read] done in 0 s

In [7]:
df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,7202016,38917982,2015-07-19,28943674,Bianca,Cute and cozy place. Perfect location to every...
1,7202016,39087409,2015-07-20,32440555,Frank,Kelly has a great room in a very central locat...
2,7202016,39820030,2015-07-26,37722850,Ian,"Very spacious apartment, and in a great neighb..."
3,7202016,40813543,2015-08-02,33671805,George,Close to Seattle Center and all it has to offe...
4,7202016,41986501,2015-08-10,34959538,Ming,Kelly was a great host and very accommodating ...

In [9]:
# 前処理
# datetime 型に変更
for c in datetime_col:
    df[c] = pd.to_datetime(df[c])

In [10]:
df.shape

(84849, 6)

In [11]:
df.dtypes

listing_id             category
id                     category
date             datetime64[ns]
reviewer_id               int64
reviewer_name            object
comments                 object
dtype: object

In [19]:
pdp.ProfileReport(df[df.columns[:5]])